-- 0. Drop existing tables and policies to start fresh
DROP TABLE IF EXISTS public.general_expenses CASCADE;
DROP TABLE IF EXISTS public.invoices CASCADE;
DROP TABLE IF EXISTS public.maintenance_logs CASCADE;
DROP TABLE IF EXISTS public.fuel_logs CASCADE;
DROP TABLE IF EXISTS public.vehicles CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;

-- 1. Profiles Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'driver',
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Vehicles Table
CREATE TABLE IF NOT EXISTS public.vehicles (
    id TEXT PRIMARY KEY, -- Plate Number or VIN
    make TEXT,
    model TEXT,
    year INTEGER,
    plate TEXT,
    status TEXT DEFAULT 'Active',
    mileage INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Fuel Logs Table
CREATE TABLE IF NOT EXISTS public.fuel_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vehicleId" TEXT REFERENCES public.vehicles(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    liters DECIMAL(10,2),
    cost DECIMAL(10,2),
    odometer INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Maintenance Logs Table
CREATE TABLE IF NOT EXISTS public.maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vehicleId" TEXT REFERENCES public.vehicles(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    cost DECIMAL(10,2),
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Invoices Table
CREATE TABLE IF NOT EXISTS public.invoices (
    id TEXT PRIMARY KEY, -- e.g., INV-001
    "clientId" TEXT,
    amount DECIMAL(10,2),
    status TEXT DEFAULT 'Pending',
    "issueDate" DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (Simplified for Dev)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow All for initial setup - WARNING: Not for Production)
CREATE POLICY "Allow All Profiles" ON public.profiles FOR ALL USING (true);
CREATE POLICY "Allow All Vehicles" ON public.vehicles FOR ALL USING (true);
CREATE POLICY "Allow All Fuel Logs" ON public.fuel_logs FOR ALL USING (true);
CREATE POLICY "Allow All Maintenance Logs" ON public.maintenance_logs FOR ALL USING (true);
CREATE POLICY "Allow All Invoices" ON public.invoices FOR ALL USING (true);

-- 6. General Expenses Table
CREATE TABLE IF NOT EXISTS public.general_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "vehicleId" TEXT REFERENCES public.vehicles(id) ON DELETE SET NULL,
    date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    cost DECIMAL(10,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Roles Table
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE,
    permissions JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.general_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Allow All General Expenses" ON public.general_expenses FOR ALL USING (true);
CREATE POLICY "Allow All Roles" ON public.roles FOR ALL USING (true);

-- ==========================================
-- Insert Default Data
-- ==========================================

-- Insert Default Roles
INSERT INTO public.roles (name, permissions) VALUES
('admin', '["view_dashboard", "manage_vehicles", "manage_expenses", "manage_fuel_logs", "manage_maintenance_logs", "manage_invoices", "manage_users", "export_reports"]'::jsonb),
('manager', '["view_dashboard", "manage_vehicles", "manage_expenses", "manage_fuel_logs", "manage_maintenance_logs", "export_reports"]'::jsonb),
('finance', '["view_dashboard", "manage_expenses", "manage_invoices", "export_reports"]'::jsonb),
('supervisor', '["manage_vehicles", "manage_expenses", "manage_fuel_logs", "manage_maintenance_logs"]'::jsonb),
('driver', '["manage_expenses", "manage_fuel_logs"]'::jsonb),
('accountant', '["view_dashboard", "manage_expenses", "manage_invoices", "export_reports"]'::jsonb)
ON CONFLICT (name) DO NOTHING;

-- Seed Vehicles
INSERT INTO public.vehicles (id, make, model, year, plate, status, mileage) VALUES
('V001', 'Volvo', 'FH16', 2022, 'ABC-1234', 'Active', 120000),
('V002', 'Scania', 'R450', 2021, 'XYZ-5678', 'Maintenance', 154000),
('V003', 'Mercedes', 'Actros', 2023, 'LMN-9012', 'Active', 45000)
ON CONFLICT (id) DO NOTHING;

-- Seed Fuel Logs
INSERT INTO public.fuel_logs ("vehicleId", date, liters, cost, odometer) VALUES
('V001', '2023-10-01', 300, 450.00, 118000),
('V001', '2023-10-05', 280, 420.00, 119500),
('V003', '2023-10-02', 350, 525.00, 44000);

-- Seed Maintenance Logs
INSERT INTO public.maintenance_logs ("vehicleId", date, description, cost, type) VALUES
('V002', '2023-09-15', 'Oil Change', 250.00, 'Routine'),
('V002', '2023-10-10', 'Brake Replacement', 1200.00, 'Repair');

-- Seed Invoices
INSERT INTO public.invoices (id, "clientId", amount, "issueDate", status) VALUES
('INV-001', 'Client A', 5000.00, '2023-10-01', 'Paid'),
('INV-002', 'Client B', 3200.00, '2023-10-05', 'Pending')
ON CONFLICT (id) DO NOTHING;
