-- 1. Profiles Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'driver',
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Vehicles Table
CREATE TABLE IF NOT EXISTS public.vehicles (
    id TEXT PRIMARY KEY, -- Plate Number or VIN
    make TEXT,
    model TEXT,
    year INTEGER,
    plate TEXT,
    status TEXT DEFAULT 'Active',
    mileage INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Fuel Logs Table
CREATE TABLE IF NOT EXISTS public.fuel_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id TEXT REFERENCES public.vehicles(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    liters DECIMAL(10,2),
    cost DECIMAL(10,2),
    odometer INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Maintenance Logs Table
CREATE TABLE IF NOT EXISTS public.maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id TEXT REFERENCES public.vehicles(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    description TEXT,
    cost DECIMAL(10,2),
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Invoices Table
CREATE TABLE IF NOT EXISTS public.invoices (
    id TEXT PRIMARY KEY, -- e.g., INV-001
    client_id TEXT,
    amount DECIMAL(10,2),
    status TEXT DEFAULT 'Pending',
    issue_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (Simplified for Dev)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow All for initial setup - WARNING: Not for Production)
CREATE POLICY "Allow All Profiles" ON public.profiles FOR ALL USING (true);
CREATE POLICY "Allow All Vehicles" ON public.vehicles FOR ALL USING (true);
CREATE POLICY "Allow All Fuel Logs" ON public.fuel_logs FOR ALL USING (true);
CREATE POLICY "Allow All Maintenance Logs" ON public.maintenance_logs FOR ALL USING (true);
CREATE POLICY "Allow All Invoices" ON public.invoices FOR ALL USING (true);
